# Generated by Django 2.2.1 on 2019-05-07 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='interface',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='collector.Interface'),
            preserve_default=False,
        ),
    ]
