# Generated by Django 2.2.1 on 2019-05-07 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_device_interface'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='interface',
        ),
        migrations.AddField(
            model_name='interface',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='collector.Device'),
            preserve_default=False,
        ),
    ]
