# Generated by Django 2.2.1 on 2019-05-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_auto_20190507_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip_addr',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
