# Generated by Django 2.2.1 on 2019-05-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_remove_link_n_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('en_pass', models.CharField(max_length=255)),
            ],
        ),
    ]
