# Generated by Django 2.2.1 on 2019-05-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0009_cdp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CDP',
        ),
    ]
