# Generated by Django 2.2.1 on 2019-05-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_remove_device_ip_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='n_hostname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interface',
            name='n_interface',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
